ma-kun92/mercari

.gitignore
Gemfile
Gemfile.lock
app/assets/javascripts/users.coffee
app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/views/users/index.html
config/routes.rb
config/unicorn.rb
test/controllers/users_controller_test.rb

Set unicorn

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/unicorn.rb

#What
自動デプロイの設定をした
#Why
効率よく開発をするため

Edit some file for deploy

---

config/deploy.rb

Fix deploy.rb

---

app/assets/stylesheets/application.scss

Edit application.scss

---

config/initializers/carrierwave.rb

Edit carrier wave .rb

---

app/uploaders/image_uploader.rb
config/routes.rb

Edit uploader

---

app/uploaders/image_uploader.rb

Edit uploader_image.rb

---

app/views/users/index.html.haml

test-deploy

---

app/views/users/index.html.haml

deploy test2

---

config/deploy.rb

Check secret.yml

---

config/deploy.rb

Edit secret.yml

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/users_show.scss
config/routes.rb

#What
Masterのファイル内にコンフリクトの記述が残ったので修正した。

Edit some conflict

---

README.md

Fix conflict

---

app/assets/stylesheets/users_show.scss
app/views/users/index.html.haml

#What
Imageタグをrailsの記法に変更しました。
#Why
本番環境でimageタグがうまく反映されなかったが、image_tagに修正するとうまく反映されたから。

index on my page for check

---

app/assets/stylesheets/user_edit.scss
app/assets/stylesheets/users_edit.scss
app/views/users/edit.html.haml
app/views/users/test.html.haml

マイページプロフィール編集画面を作成しました
プロフィール内容を編集できるようにするため

Create mypage profile

---

app/views/shared/_footer.html.haml
app/views/shared/_header.html.haml

Shared配下のファイルから.svgを＃に変更しました
#Why
本番環境で.svgが反映されないため。

Edit shared/

---

app/assets/stylesheets/users_indentification.scss
app/views/users/sessions/identification.html.haml

ユーザー確認ページを作成しました。
ユーザーのsession管理のため

Make up user identification

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/users_indentification.scss
app/views/users/sessions/identification.html.haml

Edit two view files for identificatoion

---

app/assets/stylesheets/registration_info.scss
app/views/users/test.html.haml

#What
ユーザーの会員情報登録画面を作成しました。
#Why
必須機能

Mark up registration page

---

app/assets/stylesheets/register_user_shipping.scss
app/views/users/registrations/register_user_adress.html.haml

新規登録の住所登録画面を作成しました。
#Why
必須機能のため。

Mark up register view

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/users_card.scss
app/views/users/registrations/register_usre_card.html.haml

新規登録画面の支払い登録の画面を作成した。
クレジットでの支払いをかのうにするため。

markuo-register-card

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/register_complete.scss
app/views/users/registrations/register_user_complete.html.haml

新規登録の完了画面を作成しました。
登録が完了したかユーザーに認識させるため

Make up view for register

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/registration_info.scss
app/assets/stylesheets/users_card.scss
app/views/users/edit.html.haml
app/views/users/index.html.haml
app/views/users/logout.html.haml
app/views/users/show.html.haml

add menu-bar for view_top

---

app/views/users/add_card_info.html.haml

クレジットカードの情報追加画面を作成しました。
クレジットの情報を後から登録できるようにするため。

Mark up view for add_credit-card-info

---

app/assets/stylesheets/edit_user_info.scss
app/views/users/edit_user_info.html.haml

後からユーザーの情報を変更するの画面を作成しました。
必須機能
住所が変わった時などに変更が効くようにするため

Make up view for card-info

---

app/assets/stylesheets/add_card_info.scss
app/assets/stylesheets/app_banner.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/users_edit.scss
app/views/users/add_card.html.haml
app/views/users/shared/_users_bottom_banner.html.haml

Add sone change

---

app/assets/stylesheets/registration_info.scss
app/views/users/registrations/new.html.haml

Edit users registration veiw

---

app/controllers/application_controller.rb
app/views/users/logout.html.haml

ログアウト機能を設定しました。
ユーザーがログアウトできるように

Fundation logout fanction

---

app/assets/stylesheets/users_show.scss
app/views/users/index.html.haml
app/views/users/logout.html.haml
app/views/users/show.html.haml

edit my page view

---

Gemfile

Add gem 'active_hash'

---

app/models/item.rb

Edit item.rb

---

Gemfile
Gemfile.lock

Edit gemfile

---

app/models/street_address.rb
app/models/vendor.rb

active_hashに関連した記述をコメントアウトしました

Edit model about active_hash

---

app/models/item.rb
app/models/prefecture.rb
app/models/street_address.rb
app/models/vendor.rb

Comment out about active_hash

---

app/controllers/users_controller.rb
app/models/vendor.rb
app/views/users/logout.html.haml
app/views/users/register_user_address.html.haml

Add validation for login

---

app/views/shared/_header.html.haml
app/views/users/register_user_top.html.haml
app/views/users/sessions/new.html.haml

Edit top-page-format

---

app/controllers/application_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/vendors_controller.rb

Edit some point on user

---

app/assets/javascripts/cards.js
app/assets/javascripts/cards_validation.js
app/assets/javascripts/flash.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_flash.scss
app/controllers/concerns/cards_actions.rb
app/controllers/items/deals_controller.rb
app/views/layouts/application.html.haml
app/views/shared/_subHeader.html.haml
app/views/shared/cards/_new.html.haml
db/schema.rb
spec/factories/deals.rb
spec/models/items/deals_spec.rb

#What
カード登録画面でのエラー出力
#Why
ユーザーのカード入力をスムーズに行うため

Puts error message

---

app/controllers/categories_controller.rb

未ログイン時のアイテム情報追加
出品者本人のアイテム閲覧中止

modify_categories_show

---

app/controllers/application_controller.rb
config/deploy.rb
config/deploy/production.rb

edit for basic_confirmation

---

app/controllers/application_controller.rb

Edit application.rb

---

app/assets/stylesheets/registration_info.scss
app/controllers/vendors_controller.rb
app/models/vendor.rb
app/views/shared/_header.html.haml
app/views/vendors/new.html.haml
config/locales/models/ja.yml

Edit some for vendor
